AWSTemplateFormatVersion: 2010-09-09
Description: >
  Resources needed to deploy a scheduled lambda function.
####################################################################################
Resources:
####################################################################################

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  LambdaSchedule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: >
        A schedule for the Lambda function..
      ScheduleExpression: cron(0 10 * * * *)
      State: ENABLED
      Targets:
        - Arn: !Sub ${Sns_Lambda.Arn}
          Id: LambdaSchedule

  LambdaSchedulePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Sub ${Sns_Lambda.Arn}
      Principal: 'events.amazonaws.com'
      SourceArn: !Sub ${LambdaSchedule.Arn}

  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Description: >
        Lambda function that returns 'Hello World!'
      Code:
        "S3Bucket": "My_S3_Bucket",
        "S3Key": "SNS_Lambda.zip"
      Handler: index.lambda_handler
      MemorySize: 128
      Role: !Sub ${LambdaExecutionRole.Arn}
      Runtime: python3.6

  SNSTopic:
      Type : "AWS::SNS::Topic"
      Properties: 
      TopicName : "Notification"

  MySubscription : 
    DependsOn : "SNSTopic"
    Type : "AWS::SNS::Subscription"
    Properties : 
      Endpoint : "austin.dsouza@quatiphi.com"
      Protocol : "email",
      TopicArn : !Ref SNSTopic

  
